name: Finences
description: "Manejo de Ingresos y Egresos"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  fl_chart: ^1.1.1
  google_sign_in: ^6.2.1
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - ./assets/iconGoogle.png
